drop table if exists book;
drop table if exists author;

create table book
(
    id        bigint generated by default as identity not null,
    isbn      varchar(255),
    publisher varchar(255),
    title     varchar(255),
    author_id bigint,
    primary key (id)
);

create table author
(
    id         bigint generated by default as identity not null,
    first_name varchar(255),
    last_name  varchar(255),
    primary key (id)
);
